import React, {useState} from 'react';
import {useEffect} from 'react';
import pokemonClose from '../images/Pokeball_icon.png';
import pokemonOpen from '../images/open-pokeball.png';
import nav_1 from '../images/nav_1.png';
import nav_2 from '../images/nav_2.png';
import nav_3 from '../images/nav_3.png';
import renny from '../images/renny.jpeg';
export default function NavBar() {
    const[show, setShow] = useState("");
    const[showBar, setShowBar] = useState(true);
    useEffect(() => {
        function handleClickOutside(event) {
            if (!event.target.closest('.navBar')) {
                setShow("")
               
            }
        }
    
        document.body.addEventListener('click', handleClickOutside);
    
        return () => {
            document.body.removeEventListener('click', handleClickOutside);
        };
    }, []);
    
    
    return (
     <>  
    <nav className={`navBar ${showBar? "navBar_color":""}`}>
    <img src={showBar?pokemonOpen:pokemonClose} alt="logo" onClick={()=>{setShowBar(showBar=>!showBar);setShow("")}}/>       
   {showBar && <ul >
    <li><a href="#rules" onClick={()=>show !== "Rules" ?setShow("Rules"):setShow("")}>Rules</a></li>
   <li><a href='#AI' onClick={()=>show !== "aboutAI"?setShow("aboutAI"):setShow("")}> about AI technology</a> </li>
   <li><a href='#pokemons' onClick={()=> show !=="PokemonList"? setShow("PokemonList"):setShow("")}>List of pokemons</a></li>
   <li><a href='#aboutMe' onClick={()=> show !=="aboutMe"? setShow("aboutMe"): setShow("")}>About Renny</a></li>   
    </ul>}
    </nav>
    <div>
    {show === "Rules" &&<div  className="nav_button" onClick={()=> setShow("")}><button>close</button> <Rules /></div>}
    {show === "aboutAI" && <div  className="nav_button" onClick={()=> setShow("")}><button>close</button><AboutAI/></div>}
    {show ==="PokemonList" && <div  className="nav_button" onClick={()=> setShow("")}><button>close</button> <PokemonList/></div>}
    {show ==="aboutMe" &&<div  className="nav_button" onClick={()=> setShow("")}><button>close</button> <AboutMe/></div>}
    </div>
    </> 
   )
}

function Rules (){
    return (<div className='nav_button-div'>
       <div className='nav_button-text rules'>
        <h3>Rules</h3>
        <p>1. Your avatar comes with a default pokemon. If you know the franchise, you will know which pokemon you will have. </p>
        <p>2. The AI will choose a pokemon randomly.</p>
        <p>3. The pokemon with the best movements wins.</p>
        <p>4. If you win you catch the AI pokemon.</p>
        <p>5. If you are defeated, you lose all Pokémon except the one you are battling.</p>
        <p>6. If you draw, everything stays the same, you can repeat the battle or move on to the next pokemon.</p>
        <p>7. You can play as many times as you want</p>
        <p>8. If the AI has a pokemon that you don't want to battle "scary" you can search for another pokemon in the search field.</p>
        <p>9. There are several buttons, one to move on to the next pokemon, the second to clear the table, another button to restart the game "you will lose your pokemon", and a button to stop the horrible music.</p>
        <p>10. These rules were generated by AI, the creator of the page was manipulated by me "don't blame him"</p>
        </div>
        <img src={nav_1} alt="pokemon" />
    </div>)
}

function AboutAI (){
    return (
    <div className='nav_button-div'>
        <div className='nav_button-text'>
        <h3>ABOUT AI</h3>
    <ul>
<li>the Minimax algorithm is a recursive algorithm used for decision making in game theory and artificial intelligence.
</li>
<li> The algorithm creates a tree of all possible game states, starting from the current state and extending down to states where the game is over (either a win, a loss, or a draw).
</li>
<li>It then evaluates the game-over states. It assigns a positive score (e.g., +1) to wins, a negative score (e.g., -1) to losses, and a zero score to draws.
</li>
<li>The algorithm then propagates these scores up the tree. If it's the AI's turn at a particular node, it takes the maximum score from among its children. If it's the opponent's turn, it takes the minimum score.
</li>
<li>The AI chooses the move that leads to the node with the best score.
</li>
</ul>
</div>
<img src={nav_2} alt="pokemon" />
</div>
        )
}


function PokemonList (){
    return (
    <div className='nav_button-div'>
       <div className='nav_button-text'>
        <h3>Pokemon List</h3>
        <p>There are more than 900 Pokémons, if you don't know the names, sorry, neither do I, but we can check the names here.</p>
        <a href="https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number"  target="blank">Chek it out</a>
        </div>
        <img src={nav_3} alt="pokemon" />
        </div>
        )
}

function AboutMe (){
    return (
    <div className='nav_button-div' >
        <div className='nav_button-text aboutMe'>
        <h3>About Me</h3>
        <img src={renny} alt="renny" />
        <h3>Renny Garces</h3>
        <p>I'm  Web Developer, I like to develop new ideas and learn about these inspiring technologies follow my other projects.</p>
        <p><a href="https://www.linkedin.com/in/renny-garces-marriaga/" target='blank'>Linkedin</a></p>
        <p><a href='https://github.com/RennyGarces' target='blank'>github</a></p>
        <p><a href='https://rennygarces-portofolio.vercel.app/' target='blank'> My web site</a></p>
        </div>
    </div>
        )
}       